# Generated by Django 2.2.4 on 2019-08-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Telefone1', models.CharField(max_length=50)),
                ('Cep', models.CharField(max_length=50)),
                ('Bairro', models.CharField(max_length=50)),
                ('Logradouro', models.CharField(max_length=50)),
                ('Numero', models.CharField(max_length=50)),
                ('Latitude', models.CharField(max_length=50)),
                ('Longitude', models.CharField(max_length=50)),
                ('Gestor', models.CharField(max_length=50)),
                ('Descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
