# Generated by Django 2.2.4 on 2019-08-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Observacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='setor',
            name='grupo',
            field=models.ManyToManyField(null=True, to='setor.Grupo'),
        ),
    ]
