# Generated by Django 2.2.4 on 2019-09-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0003_demandas_item_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='SetorTag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SetorTag', to='setor.Setor'),
        ),
    ]
