# Generated by Django 2.2.4 on 2019-09-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0004_tags_setortag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='SetorItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SetorItem', to='setor.Setor'),
        ),
    ]
