# Generated by Django 2.2.4 on 2019-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0005_item_setoritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='Nome',
            field=models.CharField(max_length=100),
        ),
    ]
