# Generated by Django 2.2.4 on 2019-09-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0007_demandas_prazoconclsao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='PrazoConclsao',
            field=models.DateField(blank=True, null=True, verbose_name='PrazodeConclusão'),
        ),
    ]
