# Generated by Django 2.2.4 on 2019-09-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0009_auto_20190917_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='Os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='Observacao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
