# Generated by Django 2.2.4 on 2019-09-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0010_auto_20190917_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='Observacao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
