# Generated by Django 2.2.4 on 2019-09-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0011_auto_20190917_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='Codigo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='setor',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
    ]
