# Generated by Django 2.2.4 on 2019-09-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0012_auto_20190918_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Observacao', models.TextField(max_length=500)),
                ('SetoraStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SetorStatus', to='setor.Setor')),
            ],
        ),
        migrations.AddField(
            model_name='demandas',
            name='StatusDemanda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StatusDemanda', to='setor.Status'),
        ),
    ]
