# Generated by Django 2.2.4 on 2019-09-25 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setor', '0013_auto_20190922_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='UsuarioDemanda',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioDemanda', to=settings.AUTH_USER_MODEL),
        ),
    ]
