# Generated by Django 2.2.4 on 2019-09-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0015_auto_20190925_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='SetorTag',
        ),
    ]
