# Generated by Django 2.2.4 on 2019-10-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0016_remove_tags_setortag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='TagSetor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TagSetor', to='setor.Setor'),
        ),
    ]
