# Generated by Django 2.2.4 on 2020-01-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0019_auto_20191129_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='grupo',
            field=models.ManyToManyField(null=True, related_name='sectors', to='setor.Grupo'),
        ),
    ]
