# Generated by Django 2.2.4 on 2021-01-06 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0020_auto_20200109_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('observacao', models.CharField(max_length=50)),
                ('setor_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setor.Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('fabricante', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('tombo', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setor.Setor')),
                ('tag', models.ManyToManyField(to='nti.Tags')),
            ],
        ),
    ]
