# Generated by Django 2.2.4 on 2021-01-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0020_auto_20200109_1639'),
        ('nti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('id_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nti.Equipamento')),
                ('id_setor_ant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_setor_ant', to='setor.Setor')),
                ('id_setor_atu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_setor_atu', to='setor.Setor')),
            ],
        ),
    ]
