# Generated by Django 2.2.4 on 2019-08-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Observacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Cpf', models.CharField(max_length=50)),
                ('Telefone', models.CharField(max_length=50)),
                ('tags', models.ManyToManyField(to='colaborador.Tags')),
            ],
        ),
    ]
