# Generated by Django 2.2.4 on 2019-08-10 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='SetorColaborador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor', to='setor.Setor'),
        ),
    ]
