# Generated by Django 2.2.4 on 2019-09-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0004_tags_setortag'),
        ('colaborador', '0005_auto_20190820_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='ColaboradorTag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ColaboradorTag', to='setor.Setor'),
        ),
    ]
