# Generated by Django 2.2.4 on 2019-09-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0005_item_setoritem'),
        ('colaborador', '0006_tags_colaboradortag'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='SetorAnterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SetorAnterior', to='setor.Setor'),
        ),
    ]
