# Generated by Django 2.2.4 on 2019-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0007_colaborador_setoranterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='Observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
