# Generated by Django 2.2.4 on 2019-09-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0009_auto_20190915_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='Observacao',
            field=models.TextField(blank=True, help_text='Texto a ser inserido na carta', max_length=500, null=True),
        ),
    ]
