# Generated by Django 2.2.4 on 2019-09-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0010_auto_20190915_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='ColaboradorTag',
            new_name='SetorTag',
        ),
    ]
