# Generated by Django 2.2.4 on 2019-09-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0011_auto_20190929_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='SetorTag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SetorTag', to='setor.Setor'),
        ),
    ]
