# Generated by Django 2.2.4 on 2019-11-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0012_auto_20190929_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='ObservacaoExpecificas',
            field=models.TextField(blank=True, help_text='Observações do Colaborador', max_length=500, null=True),
        ),
    ]
