# Generated by Django 2.2.4 on 2019-08-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20190817_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Descricao', models.CharField(max_length=255)),
                ('DataRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('UsuarioNota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioNota', to='usuario.Usuario')),
            ],
        ),
    ]
