# Generated by Django 2.2.4 on 2019-09-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20190824_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='Descricao',
            field=models.TextField(max_length=500),
        ),
    ]
