# Generated by Django 2.2.4 on 2019-08-25 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0002_auto_20190814_1028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Descricao', models.CharField(max_length=255)),
                ('DataRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('SetorFeed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SetorFeed', to='setor.Setor')),
                ('UsuarioFeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioFeed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
