# Generated by Django 2.2.4 on 2019-08-31 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='UsuarioFeed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioFeed', to=settings.AUTH_USER_MODEL),
        ),
    ]
